# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZeOQDMMYxUSsmowKwzztEXWJ72VOwzh
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --- CẤU HÌNH TRANG ---
st.set_page_config(page_title="WORKBank Dashboard", page_icon="📊", layout="wide")
st.title("📊 WORKBank: Dashboard Phân Tích Tương Lai Việc Làm & AI")
st.markdown("Phân tích thái độ và mức độ sẵn sàng sử dụng AI (LLM) của người lao động Hoa Kỳ.")

# --- TẢI VÀ XỬ LÝ DỮ LIỆU ---
# 2. Thành phần tải file (File Uploader) - Đổi định dạng nhận diện thành .csv
uploaded_file = st.file_uploader("Chọn một file CSV (.csv)", type=["csv"])

if uploaded_file is not None:
    try:
        # 3. Đọc dữ liệu từ file CSV bằng Pandas
        # Dùng mã hóa utf-8 hoặc latin1 để tránh lỗi font tiếng Việt nếu có
        try:
            df = pd.read_csv(uploaded_file, encoding='utf-8')
        except UnicodeDecodeError:
            df = pd.read_csv(uploaded_file, encoding='latin-1')

        st.success("Tải file CSV thành công!")

    # Xử lý các cột LLM Usage bị thiếu (NaN) thành 'Never'
    usage_cols = [col for col in df.columns if 'LLM Usage by Type' in col]
    df[usage_cols] = df[usage_cols].fillna('Never')

    return df

df = load_data()

# --- SIDEBAR: BỘ LỌC DỮ LIỆU ---
st.sidebar.header("🔍 Bộ lọc dữ liệu")

# Lọc theo Ngành nghề (Occupation)
all_occupations = sorted(df['Occupation (O*NET-SOC Title)'].dropna().unique())
selected_occ = st.sidebar.multiselect("Chọn ngành nghề (Occupations):", all_occupations, default=[])

# Lọc theo Học vấn (Education)
all_education = sorted(df['Education'].dropna().unique())
selected_edu = st.sidebar.multiselect("Chọn trình độ học vấn:", all_education, default=[])

# Áp dụng bộ lọc
df_filtered = df.copy()
if selected_occ:
    df_filtered = df_filtered[df_filtered['Occupation (O*NET-SOC Title)'].isin(selected_occ)]
if selected_edu:
    df_filtered = df_filtered[df_filtered['Education'].isin(selected_edu)]

st.sidebar.markdown(f"**Số lượng mẫu đang hiển thị: {len(df_filtered)}**")

# --- TẠO 3 TABS ---
tab1, tab2, tab3 = st.tabs(["📌 Tổng quan (Overview)", "🧠 Thái độ với AI (Attitudes)", "💻 Thói quen dùng LLM (Usage)"])

# ==========================================
# TAB 1: TỔNG QUAN
# ==========================================
with tab1:
    st.header("Thông tin chung về lực lượng lao động")

    # Thẻ KPI
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Tổng số người tham gia", f"{len(df_filtered):,}")
    col2.metric("Số lượng ngành nghề", f"{df_filtered['Occupation (O*NET-SOC Title)'].nunique()}")
    col3.metric("Độ tuổi trung bình", f"{int(df_filtered['Age'].mean())}")

    # Tính % người dùng LLM thường xuyên
    regular_users = df_filtered[df_filtered['LLM Familiarity'] == 'I use them regularly.'].shape[0]
    col4.metric("Dùng LLM thường xuyên", f"{round((regular_users/len(df_filtered))*100, 1)}%")

    st.markdown("---")

    # Biểu đồ: Phân bố theo độ tuổi và Thu nhập
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Phân bố Độ tuổi")
        fig_age = px.histogram(df_filtered, x='Age', nbins=20, color_discrete_sequence=['#4C72B0'])
        fig_age.update_layout(xaxis_title="Độ tuổi", yaxis_title="Số lượng")
        st.plotly_chart(fig_age, use_container_width=True)

    with c2:
        st.subheader("Phân bố Mức thu nhập")
        income_order = ['Under 30K', '30-60K', '60-86K', '86K-165K', 'Over 165K'] # Cập nhật theo data thực tế nếu cần
        fig_income = px.histogram(df_filtered, y='Income', category_orders={"Income": income_order}, color_discrete_sequence=['#55A868'])
        fig_income.update_layout(xaxis_title="Số lượng", yaxis_title="Thu nhập")
        st.plotly_chart(fig_income, use_container_width=True)

# ==========================================
# TAB 2: THÁI ĐỘ VỚI AI
# ==========================================
with tab2:
    st.header("Khám phá Thái độ của người lao động đối với AI")

    attitude_cols = [
        'AI Tedious Work Attitude',
        'AI Job Importance Attitude',
        'AI Daily Interest Attitude',
        'AI Suffering Attitude'
    ]

    # Gom nhóm dữ liệu cho biểu đồ Stacked Bar
    attitude_counts = []
    for col in attitude_cols:
        counts = df_filtered[col].value_counts(normalize=True) * 100
        counts.name = col.replace(" Attitude", "").replace("AI ", "")
        attitude_counts.append(counts)

    df_att = pd.DataFrame(attitude_counts).fillna(0)

    # Đảm bảo thứ tự thang đo Likert
    likert_order = ['Strongly agree', 'Somewhat agree', 'Neither agree nor disagree', 'Somewhat disagree', 'Strongly disagree']
    for col in likert_order:
        if col not in df_att.columns:
            df_att[col] = 0
    df_att = df_att[likert_order]

    st.subheader("Tỷ lệ các mức độ đồng ý theo từng khía cạnh")
    fig_att = px.bar(
        df_att,
        x=df_att.columns,
        y=df_att.index,
        orientation='h',
        barmode='stack',
        color_discrete_map={
            'Strongly agree': '#1a9850',
            'Somewhat agree': '#91cf60',
            'Neither agree nor disagree': '#ffffbf',
            'Somewhat disagree': '#fc8d59',
            'Strongly disagree': '#d73027'
        }
    )
    fig_att.update_layout(xaxis_title="% Phần trăm", yaxis_title="Khía cạnh đánh giá", legend_title="Mức độ")
    st.plotly_chart(fig_att, use_container_width=True)

# ==========================================
# TAB 3: THÓI QUEN SỬ DỤNG LLM
# ==========================================
with tab3:
    st.header("Phân tích Thói quen sử dụng LLM theo Tác vụ")

    # Định nghĩa các cột thói quen
    usage_cols = [
        'LLM Usage by Type - Information Access', 'LLM Usage by Type - Edit',
        'LLM Usage by Type - Idea Generation', 'LLM Usage by Type - Communication',
        'LLM Usage by Type - Analysis', 'LLM Usage by Type - Decision',
        'LLM Usage by Type - Coding', 'LLM Usage by Type - System Design',
        'LLM Usage by Type - Data Processing'
    ]

    # Chuyển đổi text sang điểm số (Frequency Score) để vẽ Heatmap
    freq_map = {'Daily': 4, 'Weekly': 3, 'Monthly': 2, 'Never': 1}

    df_heat = df_filtered.copy()
    for col in usage_cols:
        df_heat[col] = df_heat[col].map(freq_map)

    # Tính điểm trung bình cho từng loại tác vụ theo ngành nghề (Lấy top 15 ngành phổ biến nhất để không bị rối)
    top_occ = df_heat['Occupation (O*NET-SOC Title)'].value_counts().nlargest(15).index
    df_heat_top = df_heat[df_heat['Occupation (O*NET-SOC Title)'].isin(top_occ)]

    heatmap_data = df_heat_top.groupby('Occupation (O*NET-SOC Title)')[usage_cols].mean()

    # Làm gọn tên cột cho Heatmap
    heatmap_data.columns = [c.replace('LLM Usage by Type - ', '') for c in heatmap_data.columns]

    st.subheader("Heatmap: Tần suất sử dụng AI theo Tác vụ (Top 15 ngành nghề)")
    st.markdown("*(Thang điểm: 1 = Không bao giờ (Never), 4 = Hàng ngày (Daily))*")

    fig_heat = px.imshow(
        heatmap_data,
        labels=dict(x="Loại tác vụ", y="Ngành nghề", color="Điểm tần suất"),
        x=heatmap_data.columns,
        y=heatmap_data.index,
        color_continuous_scale='Blues',
        aspect="auto"
    )
    st.plotly_chart(fig_heat, use_container_width=True)